import { describe, it, expect } from 'vitest';
import {
  scoreCitationRelevance,
  filterCitations,
  RELEVANCE_THRESHOLD,
  type CitationCandidate,
  type RelevanceInput,
} from '../citation-relevance';

// ---------------------------------------------------------------------------
// Helper factories
// ---------------------------------------------------------------------------

function makeCandidate(overrides: Partial<CitationCandidate> = {}): CitationCandidate {
  return {
    doc_abbreviation: 'PHAK',
    heading: 'Chapter 5: Aerodynamics',
    snippet: 'Lift is generated by the differential pressure acting on the wing.',
    source: 'evidence',
    ...overrides,
  };
}

function makeInput(overrides: Partial<RelevanceInput> = {}): RelevanceInput {
  return {
    element_code: 'PA.I.A.K1',
    area: 'I',
    rating: 'private',
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// scoreCitationRelevance
// ---------------------------------------------------------------------------

describe('scoreCitationRelevance', () => {
  it('gives high score for direct element reference in snippet', () => {
    const result = scoreCitationRelevance(
      makeCandidate({ snippet: 'This covers PA.I.A.K1 — certificates and documents' }),
      makeInput(),
    );
    expect(result.score).toBeGreaterThanOrEqual(0.5);
    expect(result.reasons).toContain('direct_element_ref');
    expect(result.keep).toBe(true);
  });

  it('gives high score for task prefix reference in heading', () => {
    const result = scoreCitationRelevance(
      makeCandidate({ heading: 'PA.I.A: Pilot Qualifications' }),
      makeInput(),
    );
    expect(result.reasons).toContain('direct_element_ref');
    expect(result.keep).toBe(true);
  });

  it('gives good score for multiple area keyword matches', () => {
    const result = scoreCitationRelevance(
      makeCandidate({
        heading: 'Preflight Inspection and Airworthiness',
        snippet: 'Check the certificate, airworthiness directive compliance, and logbook entries.',
      }),
      makeInput({ area: 'I' }),
    );
    expect(result.reasons.some(r => r.startsWith('area_keywords'))).toBe(true);
    expect(result.keep).toBe(true);
  });

  it('gives universal doc bonus for PHAK', () => {
    const result = scoreCitationRelevance(
      makeCandidate({ doc_abbreviation: 'PHAK' }),
      makeInput(),
    );
    expect(result.reasons).toContain('doc_universal:PHAK');
  });

  it('gives universal doc bonus for AIM', () => {
    const result = scoreCitationRelevance(
      makeCandidate({ doc_abbreviation: 'AIM' }),
      makeInput(),
    );
    expect(result.reasons).toContain('doc_universal:AIM');
  });

  it('gives universal doc bonus for CFR', () => {
    const result = scoreCitationRelevance(
      makeCandidate({ doc_abbreviation: 'CFR' }),
      makeInput(),
    );
    expect(result.reasons).toContain('doc_universal:CFR');
  });

  it('gives rating+area bonus for IFH with instrument rating in Area VI', () => {
    const result = scoreCitationRelevance(
      makeCandidate({ doc_abbreviation: 'IFH' }),
      makeInput({ element_code: 'IR.VI.D.K1', area: 'VI', rating: 'instrument' }),
    );
    expect(result.reasons).toContain('doc_rating_area_match:IFH');
  });

  it('gives rating bonus for IPH with instrument rating', () => {
    const result = scoreCitationRelevance(
      makeCandidate({ doc_abbreviation: 'IPH' }),
      makeInput({ element_code: 'IR.I.A.K1', area: 'I', rating: 'instrument' }),
    );
    expect(result.reasons).toContain('doc_rating_match:IPH');
  });

  it('gives low doc relevance for IPH with private rating Area I', () => {
    const result = scoreCitationRelevance(
      makeCandidate({ doc_abbreviation: 'IPH', snippet: 'Generic content about procedures' }),
      makeInput({ area: 'I', rating: 'private' }),
    );
    expect(result.reasons).toContain('doc_low_relevance:IPH');
  });

  it('gives transcript source bonus', () => {
    const evidenceResult = scoreCitationRelevance(
      makeCandidate({ source: 'evidence' }),
      makeInput(),
    );
    const transcriptResult = scoreCitationRelevance(
      makeCandidate({ source: 'transcript' }),
      makeInput(),
    );
    expect(transcriptResult.score).toBeGreaterThan(evidenceResult.score);
    expect(transcriptResult.reasons).toContain('transcript_source');
  });

  it('penalizes empty snippets', () => {
    const normalResult = scoreCitationRelevance(
      makeCandidate({ snippet: 'Normal content about airworthiness certificates.' }),
      makeInput(),
    );
    const emptyResult = scoreCitationRelevance(
      makeCandidate({ snippet: '' }),
      makeInput(),
    );
    expect(emptyResult.score).toBeLessThan(normalResult.score);
    expect(emptyResult.reasons).toContain('empty_snippet');
  });

  it('penalizes no heading + no keywords + no direct ref', () => {
    const result = scoreCitationRelevance(
      makeCandidate({
        doc_abbreviation: 'OTHER',
        heading: null,
        snippet: 'Something completely unrelated to aviation.',
      }),
      makeInput({ area: 'IX' }), // postflight — very specific keywords
    );
    expect(result.reasons).toContain('no_heading_no_keywords');
  });

  it('rejects citations below threshold', () => {
    const result = scoreCitationRelevance(
      makeCandidate({
        doc_abbreviation: 'OTHER',
        heading: null,
        snippet: 'Completely irrelevant text about cooking recipes.',
      }),
      makeInput({ area: 'IX' }),
    );
    expect(result.keep).toBe(false);
    expect(result.score).toBeLessThan(RELEVANCE_THRESHOLD);
  });

  it('clamps score to [0, 1]', () => {
    // Force maximum possible score
    const result = scoreCitationRelevance(
      makeCandidate({
        doc_abbreviation: 'PHAK',
        heading: 'PA.I.A: Preflight airworthiness certificate document logbook',
        snippet: 'Preflight inspection of certificates, airworthiness directives, logbook, weather, and notam.',
        source: 'transcript',
      }),
      makeInput(),
    );
    expect(result.score).toBeLessThanOrEqual(1);
    expect(result.score).toBeGreaterThanOrEqual(0);
  });

  it('handles missing rating gracefully', () => {
    const result = scoreCitationRelevance(
      makeCandidate({ doc_abbreviation: 'IFH' }),
      makeInput({ rating: undefined }),
    );
    // Should not crash; rating match just won't apply
    expect(result.score).toBeGreaterThanOrEqual(0);
  });

  it('uses instrument-specific keywords for instrument rating Area IV', () => {
    // Instrument Area IV = Flight by Reference to Instruments (not takeoffs/landings)
    const result = scoreCitationRelevance(
      makeCandidate({
        doc_abbreviation: 'IFH',
        heading: 'Attitude Instrument Flying',
        snippet: 'The instrument scan involves checking the attitude indicator, altimeter, and heading indicator.',
      }),
      makeInput({ element_code: 'IR.IV.A.K1', area: 'IV', rating: 'instrument' }),
    );
    expect(result.reasons.some(r => r.startsWith('area_keywords'))).toBe(true);
    expect(result.keep).toBe(true);
  });

  it('uses commercial-specific keywords for commercial rating Area VIII', () => {
    // Commercial Area VIII = High-Altitude Operations (not Basic Instruments)
    const result = scoreCitationRelevance(
      makeCandidate({
        doc_abbreviation: 'PHAK',
        heading: 'Pressurization Systems',
        snippet: 'Cabin pressurization maintains cabin altitude below 8,000 feet. Supplemental oxygen is required above FL250.',
      }),
      makeInput({ element_code: 'CA.VIII.A.K1', area: 'VIII', rating: 'commercial' }),
    );
    expect(result.reasons.some(r => r.startsWith('area_keywords'))).toBe(true);
    expect(result.keep).toBe(true);
  });

  it('uses commercial emergency keywords for commercial Area IX', () => {
    const result = scoreCitationRelevance(
      makeCandidate({
        doc_abbreviation: 'PHAK',
        heading: 'Emergency Procedures',
        snippet: 'Engine failure during flight requires immediate action: establish best glide speed.',
      }),
      makeInput({ element_code: 'CA.IX.A.K1', area: 'IX', rating: 'commercial' }),
    );
    expect(result.reasons.some(r => r.startsWith('area_keywords'))).toBe(true);
    expect(result.keep).toBe(true);
  });

  it('uses instrument-specific keywords for instrument rating Area V', () => {
    // Instrument Area V = Navigation Systems (not performance maneuvers)
    const result = scoreCitationRelevance(
      makeCandidate({
        doc_abbreviation: 'IFH',
        heading: 'VOR Navigation',
        snippet: 'Tracking a VOR radial requires setting the OBS and monitoring the CDI needle deflection.',
      }),
      makeInput({ element_code: 'IR.V.A.K1', area: 'V', rating: 'instrument' }),
    );
    expect(result.reasons.some(r => r.startsWith('area_keywords'))).toBe(true);
    expect(result.keep).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// filterCitations
// ---------------------------------------------------------------------------

describe('filterCitations', () => {
  it('returns only citations above threshold sorted by score', () => {
    const candidates = [
      makeCandidate({ doc_abbreviation: 'OTHER', heading: null, snippet: 'Irrelevant cooking content' }),
      makeCandidate({ doc_abbreviation: 'PHAK', heading: 'Preflight inspection', snippet: 'Airworthiness certificates and logbook entries' }),
      makeCandidate({ doc_abbreviation: 'CFR', heading: '14 CFR Part 91', snippet: 'Aircraft airworthiness requirements and certificates' }),
    ];

    const input = makeInput({ area: 'I' });
    const { kept, filtered } = filterCitations(candidates, input);

    // PHAK and CFR should be kept; OTHER should be filtered
    expect(kept.length).toBeGreaterThanOrEqual(1);
    expect(kept.length).toBeLessThanOrEqual(3);

    // kept should be sorted by score desc
    for (let i = 0; i < kept.length - 1; i++) {
      expect(kept[i].relevance.score).toBeGreaterThanOrEqual(kept[i + 1].relevance.score);
    }

    // All kept items should be above threshold
    for (const item of kept) {
      expect(item.relevance.keep).toBe(true);
    }

    // All filtered items should be below threshold
    for (const item of filtered) {
      expect(item.relevance.keep).toBe(false);
    }
  });

  it('respects maxResults parameter', () => {
    const candidates = Array.from({ length: 10 }, (_, i) =>
      makeCandidate({
        doc_abbreviation: 'PHAK',
        heading: `Chapter ${i}: Preflight certificates airworthiness`,
        snippet: `Content about preflight certificate airworthiness inspection number ${i}.`,
      })
    );

    const { kept } = filterCitations(candidates, makeInput({ area: 'I' }), 3);
    expect(kept.length).toBeLessThanOrEqual(3);
  });

  it('returns empty kept array when all are irrelevant', () => {
    const candidates = [
      makeCandidate({ doc_abbreviation: 'OTHER', heading: null, snippet: 'Cooking recipe' }),
      makeCandidate({ doc_abbreviation: 'OTHER', heading: null, snippet: 'Basketball rules' }),
    ];

    const { kept } = filterCitations(candidates, makeInput({ area: 'IX' }));
    expect(kept.length).toBe(0);
  });

  it('prefers transcript citations in tie-breaking', () => {
    const candidates = [
      makeCandidate({
        doc_abbreviation: 'PHAK',
        heading: 'Preflight Inspection',
        snippet: 'Check airworthiness certificates and documents.',
        source: 'evidence',
      }),
      makeCandidate({
        doc_abbreviation: 'PHAK',
        heading: 'Preflight Inspection',
        snippet: 'Check airworthiness certificates and documents.',
        source: 'transcript',
      }),
    ];

    const { kept } = filterCitations(candidates, makeInput({ area: 'I' }));
    expect(kept.length).toBe(2);
    // Transcript should be first (higher score due to bonus)
    expect(kept[0].citation.source).toBe('transcript');
  });
});
